language: node_js
node_js:
  - 9
  - 8
  - 6
  - 4
before_install:
  - yarn config set no-progress
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
notifications:
  email: true
after_success: npm run coverage
